version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123       # root user password
      MYSQL_DATABASE: mydb                   # auto-create this DB
      MYSQL_USER: appuser                    # non-root user
      MYSQL_PASSWORD: user123             # non-root password
    ports:
      - "3309:3306"                          # expose MySQL to host
    volumes:
      - mysql_data:/var/lib/mysql            # store data in a volume
    networks:
      - mysql_net                            # ✅ plural here

  app:
    build: .
    container_name: my_node_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: mydb
      DB_USER: appuser
      DB_PASSWORD: user123
      DB_ROOT_PASSWORD: root123
    depends_on:
      - mysql
    networks:
      - mysql_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - mysql_net

volumes:
  mysql_data:                                # named volume for persistence

networks:
  mysql_net:                                 # ✅ plural here too
